### ISSUE TITLE
About CainGAN w/o T (1) setting

### ISSUE THREAD

**Issue by kenoharada** [TArdelean/CainGAN#2]
Thank you very much for sharing awesome work!

I would like to reproduce the result of CainGAN w/o T (1) (top row of table 2 in the paper)
(I know the selected videos may change, so I can't exactly reproduce the result)

Could you tell me the hyperparameters for that and is there any additional setting for that?

**Comment by TArdelean** [comment]
The hyperparameters used are the ones in `options.py` (default), except for K=1 (since you want to reproduce 1 shot results).
Note that CainGAN w/o T has a slightly different design since the input has fewer channels. You can't currently switch to that version with a  parsable argument. You can, though, modify the code so that the target landmark is not used in the embedder: `in_t=3` becomes `in_t=0` and you don't use `target_landmark` in `forward` method.

**Comment by kenoharada** [comment]
Thank you very much for quick response!
I modified the network architecture
